import type { ExpoConfig, ConfigContext } from 'expo/config';
import { withAndroidManifest, withDangerousMod } from '@expo/config-plugins';
import * as path from 'node:path';
import * as fs from 'node:fs';

/**
 * Android Network Security Config — split by build type.
 *
 * WHY THERE ARE TWO. A single config under `src/main/res/xml/` applies to
 * EVERY build type, release included. That is how the homelab/loopback
 * cleartext exemptions ended up shipping in production builds: an installed
 * release APK was permitted plain HTTP to 192.168.178.79, 192.168.178.21,
 * localhost, 127.0.0.1 and 10.0.2.2. On a stranger's LAN those private
 * addresses belong to somebody else's machine, so the exemption removed the
 * TLS guarantee for any traffic that ever pointed there.
 *
 * The fix relies on Android resource merging: a resource in `src/<buildType>/`
 * overrides the same-named resource in `src/main/`. `<application
 * android:networkSecurityConfig="@xml/network_security_config">` therefore
 * stays exactly as it is in the merged manifest, and resolves to:
 *
 *   release  →  src/main/res/xml/   — STRICT, no exemptions
 *   debug    →  src/debug/res/xml/  — the private-host exemptions
 *
 * SCOPE OF THE GUARANTEE. Network Security Config is enforced by the Android
 * platform network stack — `java.net`/`HttpsURLConnection`, OkHttp and Cronet
 * when they use the platform, `WebView`, and anything layered on those. It is
 * NOT a device-wide firewall: native code that opens its own sockets, or a
 * third-party stack that bundles its own TLS/HTTP implementation, is not
 * subject to it. So the correct claim is "cleartext is refused for the network
 * stacks that honour Network Security Config", not "every destination requires
 * HTTPS".
 *
 * THIS DELIBERATELY CHANGES PRODUCTION BEHAVIOUR. Release builds used to
 * permit plain HTTP to the five private hosts above; they no longer do. Any
 * release-build request to `192.168.178.79`, `192.168.178.21`, `localhost`,
 * `127.0.0.1` or `10.0.2.2` over `http://`, made through a stack that honours
 * the config, now fails with `UnknownServiceException: CLEARTEXT
 * communication not permitted`, where before it succeeded. That is the point
 * of the change, and it is a behaviour change, not a no-op.
 *
 * What is NOT touched: no endpoint, URL or host used by the app is modified,
 * and no manifest attribute is added, removed or replaced.
 * `android:usesCleartextTraffic` in the debug manifest stays irrelevant: from
 * API 24 a present networkSecurityConfig wins.
 *
 * Both stay inline (not separate template files) so `npx expo prebuild --clean`
 * regenerates them identically without relying on hand-edited files surviving
 * the wipe.
 */
const NETWORK_SECURITY_CONFIG_MAIN = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Guardian Cloud — Android Network Security Config (ALL BUILD TYPES).
  Generated by app.config.ts on prebuild. Do not edit by hand; edit the
  template inside app.config.ts instead.

  NO cleartext exemptions. Any stack that honours Network Security Config —
  java.net/HttpsURLConnection, OkHttp and Cronet over the platform, WebView —
  refuses plain HTTP here, and requires a system-trusted certificate. This is
  not a device-wide firewall: native code with its own sockets, or a library
  bundling its own TLS/HTTP implementation, is outside its scope.

  The debug build overrides this file with
  src/debug/res/xml/network_security_config.xml; release never does.

  BEHAVIOUR CHANGE: release builds previously permitted plain HTTP to
  192.168.178.79, 192.168.178.21, localhost, 127.0.0.1 and 10.0.2.2. They no
  longer do, and such requests now fail. That is intended.

  Do NOT add <domain-config> here. Development hosts belong in the debug
  override, which cannot reach a release APK.
-->
<network-security-config>
    <base-config cleartextTrafficPermitted="false">
        <trust-anchors>
            <certificates src="system"/>
        </trust-anchors>
    </base-config>
</network-security-config>
`;

const NETWORK_SECURITY_CONFIG_DEBUG = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Guardian Cloud — Android Network Security Config (DEBUG BUILD ONLY).
  Generated by app.config.ts on prebuild. Do not edit by hand.

  Overrides src/main/res/xml/network_security_config.xml for the debug build
  type only. Cleartext HTTP is allowed ONLY for these private/loopback hosts:
    - 192.168.178.79  (LAN backend / homelab dev box)
    - 192.168.178.21  (LAN backend / homelab dev box)
    - localhost       (in-device loopback)
    - 127.0.0.1       (in-device loopback — Metro over adb reverse)
    - 10.0.2.2        (Android emulator alias for host machine)
  Every other destination is refused cleartext by the stacks that honour this
  config, and requires HTTPS + valid TLS.

  Adding a public hostname here would be a security regression even in debug.
-->
<network-security-config>
    <base-config cleartextTrafficPermitted="false">
        <trust-anchors>
            <certificates src="system"/>
        </trust-anchors>
    </base-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="false">192.168.178.79</domain>
        <domain includeSubdomains="false">192.168.178.21</domain>
        <domain includeSubdomains="false">localhost</domain>
        <domain includeSubdomains="false">127.0.0.1</domain>
        <domain includeSubdomains="false">10.0.2.2</domain>
    </domain-config>
</network-security-config>
`;

/**
 * Expo config.
 *
 * We use Expo Dev Client (not Managed) so we can drop in native modules
 * later for foreground services, background upload, SQLite, etc.
 *
 * Secrets live in `.env` and are exposed to the bundle via the standard
 * `EXPO_PUBLIC_*` prefix (read directly from `process.env`). Anything that
 * must NOT reach the client MUST NOT use that prefix.
 */
export default ({ config }: ConfigContext): ExpoConfig => ({
  ...config,
  name: 'Guardian Cloud',
  slug: 'guardian-cloud',
  owner: 'amarus',
  scheme: 'guardiancloud',
  version: '0.1.0',
  orientation: 'portrait',
  userInterfaceStyle: 'automatic',
  newArchEnabled: true,
  icon: './assets/foreground.png',
  ios: {
    supportsTablet: false,
    bundleIdentifier: 'com.guardiancloud.app',
  },
  android: {
    package: 'com.guardiancloud.app',
    adaptiveIcon: {
      foregroundImage: './assets/foreground.png',
      backgroundColor: '#000000',
    },
  },
  plugins: [
    /**
     * react-native-background-actions foreground service fix.
     *
     * RNBackgroundActionsTask starts with FOREGROUND_SERVICE_TYPE_MICROPHONE
     * (0x80). Android 14+ requires the <service> declaration to explicitly
     * list every type the code requests — a missing or zero-value
     * android:foregroundServiceType causes an immediate crash:
     *   "foregroundServiceType 0x00000080 is not a subset of
     *    foregroundServiceType attribute 0x00000000"
     *
     * This plugin ensures the fix survives `npx expo prebuild`.
     */
    (config): ExpoConfig =>
      withAndroidManifest(config, (mod) => {
        const app = mod.modResults.manifest.application?.[0];
        if (!app) return mod;

        // Ensure permissions
        const manifest = mod.modResults.manifest;
        const existingPerms: string[] = (manifest['uses-permission'] ?? []).map(
          (p: { $: { 'android:name': string } }) => p.$['android:name'],
        );
        const requiredPerms = [
          'android.permission.FOREGROUND_SERVICE',
          'android.permission.FOREGROUND_SERVICE_MICROPHONE',
          'android.permission.WAKE_LOCK',
          // Android 13+ requires POST_NOTIFICATIONS to be declared in the
          // manifest before the runtime request takes effect. Without it,
          // PermissionsAndroid.request() returns 'never_ask_again' silently
          // and the foreground-service notification never appears, so the
          // user has no visible signal that background protection is active.
          'android.permission.POST_NOTIFICATIONS',
          // Lets the app open the system "ignore battery optimisations"
          // settings page so the user can grant a Doze exemption. We do
          // NOT request the exemption via system dialog (Play Store
          // policy review). The Settings screen exposes a button that
          // calls Linking.sendIntent() into this page.
          'android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS',
        ];
        for (const perm of requiredPerms) {
          if (!existingPerms.includes(perm)) {
            manifest['uses-permission'] = manifest['uses-permission'] ?? [];
            manifest['uses-permission'].push({ $: { 'android:name': perm } });
          }
        }

        // Ensure service declaration with foregroundServiceType
        const services: { $: Record<string, string> }[] = app.service ?? [];
        const svcName = 'com.asterinet.react.bgactions.RNBackgroundActionsTask';
        const existing = services.find((s) => s.$['android:name'] === svcName);
        if (existing) {
          existing.$['android:foregroundServiceType'] = 'microphone';
        } else {
          app.service = [
            ...services,
            {
              $: {
                'android:name': svcName,
                'android:foregroundServiceType': 'microphone',
              },
            },
          ];
        }

        // Point <application> at the XML resource. This single attribute
        // resolves per build type: release gets the strict main resource,
        // debug gets the override in src/debug/res/xml/. Nothing here grants
        // any exemption on its own.
        app.$['android:networkSecurityConfig'] = '@xml/network_security_config';

        return mod;
      }),
    /**
     * Write BOTH network security configs on every prebuild:
     *
     *   app/src/main/res/xml/network_security_config.xml   — strict
     *   app/src/debug/res/xml/network_security_config.xml  — dev exemptions
     *
     * Runs as a `withDangerousMod` because the config plugin API has no
     * first-class hook for arbitrary resource files. The XML bodies are the
     * constants declared at the top of this file.
     */
    (config): ExpoConfig =>
      withDangerousMod(config, [
        'android',
        async (cfg) => {
          const resXmlDir = (buildType: 'main' | 'debug') =>
            path.join(
              cfg.modRequest.platformProjectRoot,
              'app',
              'src',
              buildType,
              'res',
              'xml',
            );

          for (const [buildType, body] of [
            ['main', NETWORK_SECURITY_CONFIG_MAIN],
            ['debug', NETWORK_SECURITY_CONFIG_DEBUG],
          ] as const) {
            const dir = resXmlDir(buildType);
            await fs.promises.mkdir(dir, { recursive: true });
            await fs.promises.writeFile(
              path.join(dir, 'network_security_config.xml'),
              body,
              'utf8',
            );
          }
          return cfg;
        },
      ]),
    'expo-router',
    /**
     * Splash screen — Guardian Cloud branded boot.
     *
     * The default Expo splash is a plain white panel that clashes with
     * the dark UI and undermines the "professional safety tool" feel.
     * We pin the brand background (#0d1117 — same surface used by the
     * Home and Settings screens) and centre the existing escudo logo
     * (`assets/foreground.png`, also reused as the Android adaptive
     * icon foreground, so it already has an alpha channel and reads
     * cleanly on a dark fill).
     *
     * No JS-side `SplashScreen.preventAutoHideAsync()` is added on
     * purpose: the native splash hides as soon as the React tree
     * mounts, which is what we want — every extra millisecond before
     * the user can tap "GRABAR AHORA" is a regression on the priority
     * order in CLAUDE.md (UX bajo estrés > activación inmediata).
     *
     * Heads-up for whoever ships next: `app.config.ts` is the source
     * of truth, but the rendered splash assets live in
     * `android/app/src/main/res/...` and are regenerated by
     * `npx expo prebuild --clean`. Without a prebuild + APK rebuild
     * this block has no visible effect at runtime.
     */
    [
      'expo-splash-screen',
      {
        backgroundColor: '#0d1117',
        // Splash-specific asset, NOT the adaptive icon foreground.
        // `foreground.png` (1024x1536) wraps the escudo in ~28% L/R
        // and ~32% T/B of transparent padding — necessary for the
        // Android adaptive icon mask, but it makes the splash logo
        // look small no matter how high `imageWidth` goes (we'd just
        // be scaling padding). `splash-logo.png` is the same raster
        // recropped to a tight 540x660 canvas (~8% breathing room),
        // so `imageWidth` now controls the actual perceived shield
        // size. The adaptive icon entry up top still points to
        // `foreground.png` and is unaffected.
        image: './assets/splash-logo.png',
        // 220 — iterated down from 360 → 260 → 220 against a OnePlus 6.
        // 360 dominated, 260 still felt heavy; 220 lets the escudo
        // breathe inside the Android 12+ icon area while staying
        // clearly readable. Asset unchanged.
        imageWidth: 220,
        resizeMode: 'contain',
      },
    ],
    [
      'expo-av',
      {
        microphonePermission:
          'Allow Guardian Cloud to access the microphone to record evidence.',
      },
    ],
    // expo-audio is the active recorder for the production audio path
    // (see `app/index.tsx`). `expo-av` stays installed because the
    // `debug-camera-probe/*` screens still import `Audio` from it; once
    // those probes are migrated or removed, both this plugin entry and
    // the `expo-av` dependency can be dropped together.
    //
    // `enableBackgroundRecording: true` is required to keep the recorder
    // capturing when the activity goes to background. Without the flag,
    // expo-audio's `OnActivityEntersBackground` lifecycle hook auto-pauses
    // active recordings, which would break the "subida durante grabación"
    // invariant. The flag also makes the plugin add a dedicated foreground
    // service entry (`foregroundServiceType="microphone"`) to the
    // AndroidManifest, alongside the existing `RNBackgroundActionsTask`
    // service that owns the GC_QUEUE upload worker.
    [
      'expo-audio',
      {
        microphonePermission:
          'Allow Guardian Cloud to access the microphone to record evidence.',
        recordAudioAndroid: true,
        enableBackgroundRecording: true,
      },
    ],
    [
      'expo-camera',
      {
        cameraPermission:
          'Allow Guardian Cloud to access the camera to record video evidence.',
        microphonePermission:
          'Allow Guardian Cloud to access the microphone to record video evidence.',
        recordAudioAndroid: true,
      },
    ],
  ],
  experiments: {
    typedRoutes: true,
  },
  extra: {
    eas: {
      projectId: '772ab007-5bf6-40cc-9dbf-46c8da04a49e',
    },
  },
});
