import type { ExpoConfig, ConfigContext } from 'expo/config';
import { withAndroidManifest, withDangerousMod } from '@expo/config-plugins';
import * as path from 'node:path';
import * as fs from 'node:fs';

/**
 * Android Network Security Config — homelab/LAN cleartext exception.
 *
 * Production keeps platform-default HTTPS enforcement (cleartext disabled
 * app-wide). Plain HTTP is allowed ONLY for the explicit hosts listed in
 * <domain-config>, which are private LAN / loopback addresses used during
 * homelab development. Adding a public hostname here would be a security
 * regression.
 *
 * Kept inline (not a separate template file) so `npx expo prebuild --clean`
 * regenerates an identical `res/xml/network_security_config.xml` without
 * relying on hand-edited files surviving the wipe.
 */
const NETWORK_SECURITY_CONFIG_XML = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Guardian Cloud — Android Network Security Config.
  Generated by app.config.ts on prebuild. Do not edit by hand; edit the
  template inside app.config.ts instead.

  Cleartext HTTP is allowed ONLY for these private/loopback hosts:
    - 192.168.178.79  (LAN backend / homelab dev box)
    - localhost       (in-device loopback)
    - 10.0.2.2        (Android emulator alias for host machine)
  Every other destination still requires HTTPS + valid TLS.
-->
<network-security-config>
    <base-config cleartextTrafficPermitted="false">
        <trust-anchors>
            <certificates src="system"/>
        </trust-anchors>
    </base-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="false">192.168.178.79</domain>
        <domain includeSubdomains="false">192.168.178.21</domain>
        <domain includeSubdomains="false">localhost</domain>
        <domain includeSubdomains="false">10.0.2.2</domain>
    </domain-config>
</network-security-config>
`;

/**
 * Expo config.
 *
 * We use Expo Dev Client (not Managed) so we can drop in native modules
 * later for foreground services, background upload, SQLite, etc.
 *
 * Secrets live in `.env` and are exposed to the bundle via the standard
 * `EXPO_PUBLIC_*` prefix (read directly from `process.env`). Anything that
 * must NOT reach the client MUST NOT use that prefix.
 */
export default ({ config }: ConfigContext): ExpoConfig => ({
  ...config,
  name: 'Guardian Cloud',
  slug: 'guardian-cloud',
  scheme: 'guardiancloud',
  version: '0.1.0',
  orientation: 'portrait',
  userInterfaceStyle: 'automatic',
  newArchEnabled: true,
  icon: './assets/foreground.png',
  ios: {
    supportsTablet: false,
    bundleIdentifier: 'com.guardiancloud.app',
  },
  android: {
    package: 'com.guardiancloud.app',
    adaptiveIcon: {
      foregroundImage: './assets/foreground.png',
      backgroundColor: '#000000',
    },
  },
  plugins: [
    /**
     * react-native-background-actions foreground service fix.
     *
     * RNBackgroundActionsTask starts with FOREGROUND_SERVICE_TYPE_MICROPHONE
     * (0x80). Android 14+ requires the <service> declaration to explicitly
     * list every type the code requests — a missing or zero-value
     * android:foregroundServiceType causes an immediate crash:
     *   "foregroundServiceType 0x00000080 is not a subset of
     *    foregroundServiceType attribute 0x00000000"
     *
     * This plugin ensures the fix survives `npx expo prebuild`.
     */
    (config): ExpoConfig =>
      withAndroidManifest(config, (mod) => {
        const app = mod.modResults.manifest.application?.[0];
        if (!app) return mod;

        // Ensure permissions
        const manifest = mod.modResults.manifest;
        const existingPerms: string[] = (manifest['uses-permission'] ?? []).map(
          (p: { $: { 'android:name': string } }) => p.$['android:name'],
        );
        const requiredPerms = [
          'android.permission.FOREGROUND_SERVICE',
          'android.permission.FOREGROUND_SERVICE_MICROPHONE',
          'android.permission.WAKE_LOCK',
          // Android 13+ requires POST_NOTIFICATIONS to be declared in the
          // manifest before the runtime request takes effect. Without it,
          // PermissionsAndroid.request() returns 'never_ask_again' silently
          // and the foreground-service notification never appears, so the
          // user has no visible signal that background protection is active.
          'android.permission.POST_NOTIFICATIONS',
          // Lets the app open the system "ignore battery optimisations"
          // settings page so the user can grant a Doze exemption. We do
          // NOT request the exemption via system dialog (Play Store
          // policy review). The Settings screen exposes a button that
          // calls Linking.sendIntent() into this page.
          'android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS',
        ];
        for (const perm of requiredPerms) {
          if (!existingPerms.includes(perm)) {
            manifest['uses-permission'] = manifest['uses-permission'] ?? [];
            manifest['uses-permission'].push({ $: { 'android:name': perm } });
          }
        }

        // Ensure service declaration with foregroundServiceType
        const services: { $: Record<string, string> }[] = app.service ?? [];
        const svcName = 'com.asterinet.react.bgactions.RNBackgroundActionsTask';
        const existing = services.find((s) => s.$['android:name'] === svcName);
        if (existing) {
          existing.$['android:foregroundServiceType'] = 'microphone';
        } else {
          app.service = [
            ...services,
            {
              $: {
                'android:name': svcName,
                'android:foregroundServiceType': 'microphone',
              },
            },
          ];
        }

        // Per-domain cleartext whitelist — point <application> at the XML
        // resource. Cleartext is NOT enabled globally; the file restricts
        // HTTP to private LAN/loopback hosts only.
        app.$['android:networkSecurityConfig'] = '@xml/network_security_config';

        return mod;
      }),
    /**
     * Write `android/app/src/main/res/xml/network_security_config.xml` on
     * every prebuild. Runs as a `withDangerousMod` because the config
     * plugin API has no first-class hook for arbitrary resource files.
     * The XML body is the constant declared at the top of this file.
     */
    (config): ExpoConfig =>
      withDangerousMod(config, [
        'android',
        async (cfg) => {
          const xmlDir = path.join(
            cfg.modRequest.platformProjectRoot,
            'app',
            'src',
            'main',
            'res',
            'xml',
          );
          await fs.promises.mkdir(xmlDir, { recursive: true });
          await fs.promises.writeFile(
            path.join(xmlDir, 'network_security_config.xml'),
            NETWORK_SECURITY_CONFIG_XML,
            'utf8',
          );
          return cfg;
        },
      ]),
    'expo-router',
    [
      'expo-av',
      {
        microphonePermission:
          'Allow Guardian Cloud to access the microphone to record evidence.',
      },
    ],
    [
      'expo-camera',
      {
        cameraPermission:
          'Allow Guardian Cloud to access the camera to record video evidence.',
        microphonePermission:
          'Allow Guardian Cloud to access the microphone to record video evidence.',
        recordAudioAndroid: true,
      },
    ],
  ],
  experiments: {
    typedRoutes: true,
  },
});
