/**
 * Best-effort session manifest generator.
 *
 * After a Drive-backed session is marked completed, this module derives a
 * JSON manifest from the chunks that are already on Drive and uploads it
 * to the same Drive folder as the chunks. The manifest is a DERIVED
 * artifact:
 *
 *   - it is NOT the source of truth for the upload pipeline,
 *   - failure to generate or upload it MUST NOT fail completion,
 *   - missing manifests are tolerated by future discovery flows.
 *
 * Why a manifest? To enable cross-device recovery (see /docs roadmap):
 * when the user installs Guardian Cloud on a new phone and connects the
 * same Google Drive, the manifest is the small, self-describing index
 * that lets the new device know which sessions exist and what chunks
 * compose each one.
 *
 * Strict isolation contract:
 *   - never throws (no exception escapes `tryGenerateManifest`)
 *   - never modifies sessions/chunks rows
 *   - never touches the upload worker, queue, recovery, export, foreground
 *     service, AudioEngine or any mobile code
 *   - one Drive upload per session at completion time, nothing else
 *   - no Drive idempotency on the manifest itself: a retry that races
 *     past the SESSION_ALREADY_COMPLETED gate is structurally prevented
 *     by `sessions.service.ts` returning 409 before this is reached.
 *     If two manifests somehow land in Drive, discovery picks the most
 *     recent — handled in a later commit, not here.
 */

import { Buffer } from 'node:buffer';

import { AppError } from '../errors/AppError.js';
import { logger } from '../utils/logger.js';
import {
  getOwnedSession,
  type CompleteSessionResult,
  type SessionMode,
  type SessionRow,
} from './sessions.service.js';
import { getDestinationWithSecretForUser } from './destinations.service.js';
import { listChunksForSession, type ChunkRow } from './chunks.service.js';
import {
  ensureRootFolder,
  uploadOrReplaceFile,
  withDriveRetry,
} from './drive.service.js';

const MANIFEST_SCHEMA = 'guardian-cloud.manifest.v2';

/**
 * Triggers for incremental (partial) manifest writes. Mirrored exactly in
 * `routes/chunks.routes.ts` — the hook there decides when to fire
 * `tryGenerateIncrementalManifest` based on the new uploaded-chunks count
 * after a chunk's status transitions to 'uploaded'. Kept here so the
 * thresholds live with the manifest service that consumes them.
 *
 *   - count === 1            → first chunk uploaded for this session
 *   - count % 10 === 0       → every 10 uploads (10, 20, 30, ...)
 *
 * Effect for a 5 MB / 40-chunk video session: ~5 incremental writes
 * (1, 10, 20, 30, 40) plus the final write at /complete. For a long
 * audio session at 450 chunks: ~46 incremental writes. Each write
 * overwrites the same Drive file by name, so Drive ends with EXACTLY
 * one manifest per session regardless of write count.
 */
export function shouldEmitIncrementalManifest(count: number): boolean {
  if (count <= 0) return false;
  if (count === 1) return true;
  return count % 10 === 0;
}

export interface ManifestChunk {
  chunk_index: number;
  hash: string;
  size: number;
  /**
   * Deterministic Drive filename of the chunk's bytes. Reconstructable
   * from (session_id, chunk_index, hash) — see `chunkFileName`. Discovery
   * on a different device uses this to locate chunks in Drive by name
   * without depending on Drive `file_id` (`remote_reference` is
   * intentionally NOT in the manifest to avoid coupling the manifest
   * shape to Drive internals).
   */
  file_name: string;
  /**
   * G3'' — medium of THIS chunk's bytes. Required in v2: every unit of
   * evidence describes itself, so no consumer has to infer the medium
   * from the session.
   *
   * A v1 manifest carries no per-chunk medium. Its parser propagates the
   * session-level `mode`, which is authoritative *there* because no
   * client able to mix media in one session has ever existed.
   */
  media: 'video' | 'audio';
}

export interface SessionManifest {
  schema: typeof MANIFEST_SCHEMA;
  session_id: string;
  destination_type: 'drive';
  created_at: string;
  /**
   * Session completion timestamp. Set to an ISO string when the manifest
   * was generated by the /complete path (final manifest). `null` when
   * generated by an incremental write during recording (partial
   * manifest). Discovery uses this together with `is_partial` to render
   * the recovery list's "Protegido" vs "Parcial" badge.
   */
  completed_at: string | null;
  chunk_count: number;
  chunks: ManifestChunk[];
  /**
   * True when this manifest was written during recording (before
   * /complete) and the session may receive more chunks. Old manifests
   * persisted before this field existed are treated as `false` by the
   * discovery parser (i.e., complete) — preserves backward compatibility.
   */
  is_partial?: boolean;
  /**
   * Monotonically increasing sequence per session. Equals the
   * uploaded-chunks count at the time of write; useful for debug
   * cross-referencing logs across incremental updates.
   */
  manifest_seq?: number;
  /**
   * ISO timestamp of when this manifest was written. Distinct from
   * `completed_at` (which only fires at /complete) and from Drive's
   * own `modifiedTime` (which the parser does not see at parse time).
   * Used by the discovery sort to order incomplete sessions sensibly
   * even when `completed_at` is null.
   */
  last_updated_at?: string;
}

/**
 * Deterministic chunk filename used by the upload proxy.
 *
 * MUST stay byte-for-byte identical to the formula in
 * `routes/destinations.routes.ts` (~line 731). If either side changes
 * independently the unit test in `tests/unit/manifest.service.test.ts`
 * fails — that pin is intentional. We intentionally do NOT import the
 * source side: the upload proxy is the canonical writer and this is the
 * read-side reconstruction, so duplication with a pinned test is safer
 * than a shared helper that drags the upload hot path into a new
 * dependency.
 */
export function chunkFileName(
  sessionId: string,
  chunkIndex: number,
  hash: string,
): string {
  const paddedIndex = String(chunkIndex).padStart(6, '0');
  const shortHash = hash.slice(0, 12);
  return `${sessionId}_${paddedIndex}_${shortHash}.chunk`;
}

/**
 * Subset of `SessionRow` the builder actually needs. Lets callers pass a
 * fixture without filling every column, and pins the contract tighter for
 * the unit test.
 */
interface SessionLite {
  id: string;
  mode: SessionMode;
  created_at: string;
}

/**
 * Pure builder. Filters chunks to those already on Drive (uploaded AND
 * carrying a non-null `remote_reference`) so the manifest only ever
 * describes evidence that actually exists in cloud storage. Sorts by
 * `chunk_index` ascending and reports `chunk_count` based on the
 * FILTERED set length, not the raw count from the chunks table.
 *
 * The `completedAt` argument is:
 *   - an ISO string for the final manifest written at /complete
 *   - `null` for incremental manifests written during recording
 *
 * `lastUpdatedAt` is the wall-clock time at which the write is happening
 * and is always present on the produced manifest. Callers pass a fresh
 * `new Date().toISOString()` so the consumer can sort partial manifests
 * sensibly without relying on Drive's `modifiedTime`.
 *
 * Side-effect free. Exposed for unit testing.
 */
export function buildManifest(
  session: SessionLite,
  completedAt: string | null,
  chunks: ChunkRow[],
  options?: { isPartial?: boolean; lastUpdatedAt?: string },
): SessionManifest {
  const uploaded = chunks
    .filter((c) => c.status === 'uploaded' && !!c.remote_reference)
    .sort((a, b) => a.chunk_index - b.chunk_index)
    .map<ManifestChunk>((c) => {
      // G3'' — v2 describes the medium PER CHUNK, and refuses to guess.
      // A row whose medium was never declared cannot be described, and
      // deriving it from `session.mode` would reintroduce exactly the
      // session-level claim v2 exists to remove. Fail closed.
      if (c.media !== 'video' && c.media !== 'audio') {
        throw new AppError(
          500,
          'MANIFEST_CHUNK_MEDIA_UNKNOWN',
          `Cannot describe chunk ${c.chunk_index}: medium not declared`,
        );
      }
      return {
        chunk_index: c.chunk_index,
        hash: c.hash,
        size: c.size,
        file_name: chunkFileName(session.id, c.chunk_index, c.hash),
        media: c.media,
      };
    });

  // G3'' — v2 carries NO session-level `mode` and NO `format`.
  //
  // `sessions.mode` still exists and still means what it always meant:
  // the medium the capture STARTED with, declared once by the client.
  // What it cannot do is stand for the medium of every chunk, so it is
  // not restated here. `format` went with it: it was derived from
  // `mode`, and had no reader anywhere in the system.
  const manifest: SessionManifest = {
    schema: MANIFEST_SCHEMA,
    session_id: session.id,
    destination_type: 'drive',
    created_at: session.created_at,
    completed_at: completedAt,
    chunk_count: uploaded.length,
    chunks: uploaded,
  };

  if (options?.isPartial) {
    manifest.is_partial = true;
  }
  // `manifest_seq` is intentionally the chunk_count value (uploaded
  // chunks at write time). It's a debug aid, not a strict counter;
  // a future skipped trigger would just leave gaps in the sequence.
  manifest.manifest_seq = uploaded.length;
  manifest.last_updated_at = options?.lastUpdatedAt ?? new Date().toISOString();

  return manifest;
}

/**
 * Best-effort manifest generation + upload to Drive. Never throws.
 *
 * Gates (skip on first failure, each logged with a stable reason):
 *   1. session row readable
 *   2. destination_type === 'drive'
 *   3. user has a connected Drive destination with a refresh_token
 *   4. chunks listing succeeds
 *   5. there is at least one uploaded chunk to manifest
 *
 * On success: `GC_MANIFEST_GENERATED` with size + chunk count + upload_ms.
 * On any failure: `GC_MANIFEST_FAILED` with a stable reason. The
 * completion path is untouched in both cases.
 */
export async function tryGenerateManifest(
  userId: string,
  sessionId: string,
  completed: CompleteSessionResult,
): Promise<void> {
  let session: SessionRow;
  try {
    session = await getOwnedSession(userId, sessionId);
  } catch (err) {
    logger.warn(
      {
        op: 'manifest.generate',
        sessionId,
        reason: 'session_lookup_failed',
        err: err instanceof Error ? err.message : String(err),
      },
      'GC_MANIFEST_FAILED',
    );
    return;
  }

  if (session.destination_type !== 'drive') {
    logger.info(
      {
        op: 'manifest.generate',
        sessionId,
        reason: 'not_drive',
        destination_type: session.destination_type,
      },
      'GC_MANIFEST_SKIPPED',
    );
    return;
  }

  let dest;
  try {
    dest = await getDestinationWithSecretForUser(userId, 'drive');
  } catch (err) {
    logger.warn(
      {
        op: 'manifest.generate',
        sessionId,
        reason: 'destination_lookup_failed',
        err: err instanceof Error ? err.message : String(err),
      },
      'GC_MANIFEST_FAILED',
    );
    return;
  }

  if (!dest) {
    logger.info(
      { op: 'manifest.generate', sessionId, reason: 'no_drive_destination' },
      'GC_MANIFEST_SKIPPED',
    );
    return;
  }
  if (dest.status !== 'connected') {
    logger.info(
      {
        op: 'manifest.generate',
        sessionId,
        reason: 'drive_not_connected',
        status: dest.status,
      },
      'GC_MANIFEST_SKIPPED',
    );
    return;
  }
  if (!dest.refresh_token) {
    logger.info(
      { op: 'manifest.generate', sessionId, reason: 'no_refresh_token' },
      'GC_MANIFEST_SKIPPED',
    );
    return;
  }

  let chunks: ChunkRow[];
  try {
    chunks = await listChunksForSession(userId, sessionId);
  } catch (err) {
    logger.warn(
      {
        op: 'manifest.generate',
        sessionId,
        reason: 'list_chunks_failed',
        err: err instanceof Error ? err.message : String(err),
      },
      'GC_MANIFEST_FAILED',
    );
    return;
  }

  const manifest = buildManifest(
    { id: session.id, mode: session.mode, created_at: session.created_at },
    completed.completed_at,
    chunks,
  );

  if (manifest.chunk_count === 0) {
    logger.info(
      { op: 'manifest.generate', sessionId, reason: 'no_uploaded_chunks' },
      'GC_MANIFEST_SKIPPED',
    );
    return;
  }

  const manifestBytes = Buffer.from(JSON.stringify(manifest, null, 2), 'utf8');
  const fileName = `${session.id}_manifest.json`;
  const refreshToken = dest.refresh_token;
  const cachedFolderId = dest.folder_id;

  const t_start = Date.now();
  try {
    const result = await withDriveRetry(refreshToken, async (accessToken) => {
      // Self-heal: if folder_id is null (legacy destination row, or user
      // deleted the folder by hand), recreate the root folder. We do NOT
      // persist it back to `destinations` from this best-effort path —
      // the canonical upload route owns that responsibility and will fix
      // it on the next chunk upload.
      const folderId = cachedFolderId ?? (await ensureRootFolder(accessToken));
      // `uploadOrReplaceFile` keeps Drive at exactly ONE manifest per
      // session: if an incremental write already created a file under
      // this name during recording, this overwrites its content with
      // the final manifest. If none exists, it creates a fresh file.
      // Either way the discovery pass sees exactly one file.
      return await uploadOrReplaceFile(
        accessToken,
        folderId,
        fileName,
        manifestBytes,
        'application/json',
      );
    });
    logger.info(
      {
        op: 'manifest.generate',
        sessionId,
        file_id: result.file_id,
        size: manifestBytes.length,
        chunk_count: manifest.chunk_count,
        upload_ms: Date.now() - t_start,
      },
      'GC_MANIFEST_GENERATED',
    );
  } catch (err) {
    logger.warn(
      {
        op: 'manifest.generate',
        sessionId,
        reason: 'drive_upload_failed',
        err: err instanceof Error ? err.message : String(err),
        upload_ms: Date.now() - t_start,
      },
      'GC_MANIFEST_FAILED',
    );
  }
}

/**
 * Incremental (partial) manifest generation. Best-effort, never throws.
 *
 * Triggered fire-and-forget from `POST /chunks` after a chunk transitions
 * to `status='uploaded'`. The handler counts uploaded chunks server-side
 * and invokes this function when `shouldEmitIncrementalManifest(count)`
 * returns true (count === 1 OR count % 10 === 0).
 *
 * Differences from `tryGenerateManifest`:
 *   - `completed_at` is set to `null` and `is_partial` to `true`
 *   - skipped if the session is already completed server-side (the
 *     /complete path owns the final manifest and races against the
 *     last few in-flight chunk uploads — defer to it)
 *   - logs `GC_INCREMENTAL_MANIFEST_*` keys distinct from
 *     `GC_MANIFEST_*` so operators can grep them apart
 *
 * Drive cost per call: 1 `findFileByName` + 1 PATCH (or POST if first
 * write). Strictly bounded by the trigger frequency in the route hook
 * (~6 calls per typical session). Fire-and-forget — the chunk upload
 * response is not blocked on this work.
 *
 * Strict isolation contract: identical to `tryGenerateManifest`. Never
 * touches GC_QUEUE, the upload worker, recovery, export, foreground
 * service, AudioEngine, or any mobile code.
 */
export async function tryGenerateIncrementalManifest(
  userId: string,
  sessionId: string,
): Promise<void> {
  let session: SessionRow;
  try {
    session = await getOwnedSession(userId, sessionId);
  } catch (err) {
    logger.warn(
      {
        op: 'manifest.generate_incremental',
        sessionId,
        reason: 'session_lookup_failed',
        err: err instanceof Error ? err.message : String(err),
      },
      'GC_INCREMENTAL_MANIFEST_FAILED',
    );
    return;
  }

  // Session is already completed: the /complete handler is or will be
  // writing the FINAL manifest. Skip to avoid a race where an in-flight
  // chunk upload's incremental write lands AFTER the final and reverts
  // the file to a partial-looking state. The final path uses the same
  // `uploadOrReplaceFile` against the same filename, so last-write-wins.
  // This gate prevents the partial from being the "last write".
  if (session.completed_at !== null) {
    logger.info(
      {
        op: 'manifest.generate_incremental',
        sessionId,
        reason: 'already_completed',
      },
      'GC_INCREMENTAL_MANIFEST_SKIPPED',
    );
    return;
  }

  if (session.destination_type !== 'drive') {
    logger.info(
      {
        op: 'manifest.generate_incremental',
        sessionId,
        reason: 'not_drive',
        destination_type: session.destination_type,
      },
      'GC_INCREMENTAL_MANIFEST_SKIPPED',
    );
    return;
  }

  let dest;
  try {
    dest = await getDestinationWithSecretForUser(userId, 'drive');
  } catch (err) {
    logger.warn(
      {
        op: 'manifest.generate_incremental',
        sessionId,
        reason: 'destination_lookup_failed',
        err: err instanceof Error ? err.message : String(err),
      },
      'GC_INCREMENTAL_MANIFEST_FAILED',
    );
    return;
  }

  if (!dest || dest.status !== 'connected' || !dest.refresh_token) {
    logger.info(
      {
        op: 'manifest.generate_incremental',
        sessionId,
        reason: dest ? `drive_${dest.status}` : 'no_drive_destination',
      },
      'GC_INCREMENTAL_MANIFEST_SKIPPED',
    );
    return;
  }

  let chunks: ChunkRow[];
  try {
    chunks = await listChunksForSession(userId, sessionId);
  } catch (err) {
    logger.warn(
      {
        op: 'manifest.generate_incremental',
        sessionId,
        reason: 'list_chunks_failed',
        err: err instanceof Error ? err.message : String(err),
      },
      'GC_INCREMENTAL_MANIFEST_FAILED',
    );
    return;
  }

  // Build with completed_at: null and is_partial: true. The builder also
  // sets `manifest_seq` from the uploaded count and `last_updated_at`
  // from the current wall clock — both new fields, both optional.
  const manifest = buildManifest(
    { id: session.id, mode: session.mode, created_at: session.created_at },
    /*completedAt*/ null,
    chunks,
    { isPartial: true },
  );

  if (manifest.chunk_count === 0) {
    // Nothing to manifest yet (chunks all pending/failed). The route's
    // shouldEmitIncrementalManifest gate makes this rare — it fires
    // when a chunk lands as 'uploaded' — but a race between the
    // route's count and our listChunks read can produce zero. Skip.
    logger.info(
      {
        op: 'manifest.generate_incremental',
        sessionId,
        reason: 'no_uploaded_chunks',
      },
      'GC_INCREMENTAL_MANIFEST_SKIPPED',
    );
    return;
  }

  const manifestBytes = Buffer.from(JSON.stringify(manifest, null, 2), 'utf8');
  const fileName = `${session.id}_manifest.json`;
  const refreshToken = dest.refresh_token;
  const cachedFolderId = dest.folder_id;

  const t_start = Date.now();
  try {
    const result = await withDriveRetry(refreshToken, async (accessToken) => {
      const folderId =
        cachedFolderId ?? (await ensureRootFolder(accessToken));
      return await uploadOrReplaceFile(
        accessToken,
        folderId,
        fileName,
        manifestBytes,
        'application/json',
      );
    });
    logger.info(
      {
        op: 'manifest.generate_incremental',
        sessionId,
        file_id: result.file_id,
        size: manifestBytes.length,
        chunk_count: manifest.chunk_count,
        manifest_seq: manifest.manifest_seq,
        upload_ms: Date.now() - t_start,
      },
      'GC_INCREMENTAL_MANIFEST_GENERATED',
    );
  } catch (err) {
    logger.warn(
      {
        op: 'manifest.generate_incremental',
        sessionId,
        reason: 'drive_upload_failed',
        err: err instanceof Error ? err.message : String(err),
        upload_ms: Date.now() - t_start,
      },
      'GC_INCREMENTAL_MANIFEST_FAILED',
    );
  }
}
